framework:
    cache:
        pools:
            cache.annotations:
                adapter: cache.adapter.doctrine
                provider: oro_cache.annotations
            cache.serializer:
                adapter: cache.adapter.doctrine
                provider: oro_cache.serializer
            cache.validator:
                adapter: cache.adapter.doctrine
                provider: oro_cache.validator

            # These pools are not an active pool of caches, but only describe the structure of child caches.
            # This is necessary in order to be able to describe caches with unique namespaces.
            #
            # See Oro\Bundle\CacheBundle\DependencyInjection\Compiler\CachePoolConfigurationPass
            oro.data.cache:
                adapters:
                    - oro.cache.adapter.array
                    - oro.cache.adapter.persistent
            oro.data.cache.without_memory_cache:
                adapter: oro.cache.adapter.persistent

    annotations:
        cache: php_array
