services:
    _defaults:
        public: true

    Oro\Bundle\ImapBundle\Controller\ConnectionController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
            - { name: container.service_subscriber, id: 'oro_imap.manager.controller.connection' }
            - { name: container.service_subscriber, id: 'translator' }
            - { name: container.service_subscriber, id: 'oro_security.encoder.default' }
            - { name: container.service_subscriber, id: 'oro_imap.connector.factory' }

    Oro\Bundle\ImapBundle\Controller\AbstractAccessTokenController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }

    Oro\Bundle\ImapBundle\Controller\MicrosoftAccessTokenController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
            - { name: container.service_subscriber, id: 'oro_imap.microsoft_oauth_provider' }
            - { name: container.service_subscriber, id: 'oro_imap.microsoft_oauth_scope_provider' }

    Oro\Bundle\ImapBundle\Controller\GmailAccessTokenController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
            - { name: container.service_subscriber, id: 'oro_imap.google_oauth_provider' }

    Oro\Bundle\ImapBundle\Controller\CheckConnectionController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
            - { name: container.service_subscriber, id: 'oro_imap.manager.controller.connection' }
