services:
    _defaults:
        tags:
            - { name: oro_message_queue.topic }

    Oro\Bundle\DataGridBundle\Async\Topic\DatagridPreExportTopic: ~
    Oro\Bundle\DataGridBundle\Async\Topic\DatagridExportTopic: ~
