styles:
    inputs:
        - 'bundles/orodatagrid/blank/scss/variables/no-data-config.scss'
        - 'bundles/orodatagrid/blank/scss/variables/datagrid-table-config.scss'
        - 'bundles/orodatagrid/blank/scss/variables/datagrid-header-cell-config.scss'
        - 'bundles/orodatagrid/blank/scss/variables/datagrid-body-cell-config.scss'
        - 'bundles/orodatagrid/blank/scss/variables/more-bar-holder-config.scss'
        - 'bundles/orodatagrid/blank/scss/variables/data-blank-content-config.scss'

        - 'bundles/orodatagrid/blank/scss/components/data-blank-content.scss'
        - 'bundles/orodatagrid/blank/scss/styles.scss'

datagrid_5_0_styles:
    inputs:
        - 'bundles/orodatagrid/blank/scss/settings/global-settings-5-0.scss'
        - 'bundles/orodatagrid/blank/scss/components/datagrid-body-cell-5-0.scss'
    output: 'css/datagrid_5.0.css'
