search:
    Oro\Bundle\EmailBundle\Entity\EmailUser:
        alias: oro_email
        label: Emails
        search_template: '@OroEmail/Email/searchResult.html.twig'
        route:
            name: oro_email_thread_view
            parameters:
                id: email.id
        fields:
            -
                name: email
                relation_type: many-to-one
                relation_fields:
                    -
                        name: subject
                        target_type: text
                        target_fields: [subject]
