services:
    _defaults:
        tags:
            - { name: oro_message_queue.topic }

    Oro\Component\MessageQueue\Job\Topic\RootJobStoppedTopic: ~
    Oro\Component\MessageQueue\Job\Topic\CalculateRootJobStatusTopic: ~
